[graphql]
update_dq_statement_mutation = '''
mutation UpdateDataQualityStatement(
  $ref: ItemReference!,
  $quality: DataQualityStatementInput!
) {
  updateDataQualityStatement(
    ref: $ref,
    quality: $quality
  ) {
      id
      type
      key
      name
      quality {
        originator
        syntheticResult
        trustScore
        dashboardLink
        checks {
          name
          family
          description: description {content}
          result
          lastExecutionTime
          checkLink
        }
      }
    }
  }
'''